theme: jekyll-theme-hacker
title: irem betul kocak's Progress Journal
description: This journal is created for IE 582 Fall23.

[Jupyter Notebook Example HTML](DataMining- HW1-Koçak-2.html)
[python code](/Users/irembetulkocak/Downloads/DataMining- HW1-Koçak.py )
