theme: jekyll-theme-hacker
title: irem betul kocak's Progress Journal
description: This journal is created for IE 582 Fall23.

[Jupyter Notebook Example HTML](fDataMining- HW1-Koçak-2.html)
[python code](fall-23-irembetulkocak/DataMining- HW1-Koçak.py )
