theme: jekyll-theme-hacker
title: irem betul kocak's Progress Journal
description: This journal is created for IE 582 Fall23.

[Jupyter Notebook Example HTML](files/DataMining- HW1-Koçak-2.html): The .pdf file is in a folder called files.
[Python Example Script](https://github.com/BU-IE-582/fall-23-ilaydacelenkk/blob/main/files/DataMining- HW1-Koçak.py): .ipynb script is in a folder called files.


