theme: jekyll-theme-hacker
title: irem betul kocak's Progress Journal
description: This journal is created for IE 582 Fall23.

[Jupyter Notebook Example HTML](files/DataMining- HW1-Koçak-2.html):
[Python Example Script](https://github.com/BU-IE-582/fall-23-irembetulkocak/blob/main/DataMining-%20HW1-Koçak.ipynb): .ipynb script is in a folder called files.


